on: push
jobs:
  Send-email:
    runs-on: ubuntu-latest
    steps: 
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Audioxide album anniversaries
          to: fred@audioxide.com
          from: Martin the Deficient Virtual Assistant
          body: Hello. I am Martin the Deficient Virtual Assistant. I have been programmed to say I hope you are well.
          # html_body: file://README.html
          # convert_markdown: true